apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mocktrics-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: mocktrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mocktrics-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - -f
        - /opt/mocktrics-exporter/config.yaml
        ports:
        - name: http-api
          containerPort: 8080
          protocol: TCP
        - name: http-metrics
          containerPort: 8000
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /opt/mocktrics-exporter/config.yaml
          subPath: config
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
      {{- if and (hasKey .Values "tolerations") (gt (len .Values.tolerations) 0) }}
      tolerations:
      {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
