{{-if  .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $annotation := .Values.persistence.annotations }}
  {{toYaml $annotation | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: mocktrics-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- range $label := .Values.persistence.labels }}
    {{toYaml $label | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- range $mode := .Values.persistence.accessModes }}
    - {{ $mode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }} 
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
